version: '3'
services:
  db:
    container_name: typeorm_db
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: api-typeorm
    volumes:
      - ./pddata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    container_name: typeorm_api
    restart: always
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db